name: 'SWM GitHub Actions Basic' # workflow의 이름 / github api를 통해 이름으로 실행 가능

on: push # on: event ex) ['push', 'pull']

jobs:
    first-job:
        name: 'First Job'

        runs-on: ubuntu-latest # build machine (Linux, Windows, IOS 등 가능)

        steps:
        - name: Say Hello World 1 # yaml에서 - 는 array를 나타냄
            shell: bash
            run: |
                echo "Hello World from step 1"
        
        - name: Say Hello World 2
            shell: pwsh # Power Shell
            run: |
                echo "Hello World from step 2"