name: 'SWM GitHub Actions Basic' # workflow의 이름 / github api를 통해 이름으로 실행 가능

on: push # on: event ex) ['push', 'pull']

env:
    GLOBAL_LEVEL: "This value comes from the GLOBAL level"

jobs:
    first-job:
        name: 'First Job'

        runs-on: ubuntu-latest # build machine (Linux, Windows, IOS 등 가능)

        env:
            JOB_LEVEL_1: "This value comes from othe JOB level 1"

        steps:
        - name: Say Hello World 1 # yaml에서 - 는 array를 나타냄
            shell: bash

            env:
                STEP_LEVEL_1: "This values comes from the STEP level 1"

            run: |
                echo "Hello World from step 1"
                echo "Global level: ${{env.GLOBAL_LEVEL}}"
                echo "Job level 1: ${{env.JOB_LEVEL_1}}"
                echo "Job level 2: ${{env.JOB_LEVEL_2}}"
                echo "Step level 1: ${{env.STEP_LEVEL_1}}"
                echo "Step level 2: ${{env.STEP_LEVEL_2}}"
        
        - name: Say Hello World 2
            shell: pwsh # Power Shell

            env:
                STEP_LEVEL_2: "This values comes from the STEP level 2"

            run: |
                echo "Hello World from step 2"
    
    second-job:
        name: 'Second Job'

        runs-on: ubuntu-latest # build machine (Linux, Windows, IOS 등 가능)

        env:
            JOB_LEVEL_1: "This value comes from othe JOB level 1"

        steps:
        - name: Say Hello World 1 # yaml에서 - 는 array를 나타냄
            shell: bash

            env:
                STEP_LEVEL_1: "This values comes from the STEP level 1"

            run: |
                echo "Hello World from step 1"
                echo "Global level: ${{env.GLOBAL_LEVEL}}"
                echo "Job level 1: ${{env.JOB_LEVEL_1}}"
                echo "Job level 2: ${{env.JOB_LEVEL_2}}"
                echo "Step level 1: ${{env.STEP_LEVEL_1}}"
                echo "Step level 2: ${{env.STEP_LEVEL_2}}"
        
        - name: Say Hello World 2
            shell: pwsh # Power Shell

            env:
                STEP_LEVEL_2: "This values comes from the STEP level 2"

            run: |
                echo "Hello World from step 2"