name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    # - name: Send message to Webex space
    #   shell: bash
    #   run: |
    #     curl --location --request POST 'https://webexapis.com/v1/messages' \
    #     --header 'Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}' \
    #     --header 'Content-Type: application/json' \
    #     --data-raw '{
    #       "roomId": "${{ secrets.ROOM_ID }}",
    #       "text": "깃헙 액션 101 워크샵에서 보내는 메시지 입니다. from: ${{ github.repository }}"
    #     }'
    
    - name: Post Message to Webex Room
      uses: chrivand/action-webex-js@main
      env:
        WEBEX_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        WEBEX_ROOM_ID: ${{ secrets.ROOM_ID }}
        MARKDOWN_MESSAGE: "**Hello, world! You just ran an action from ${{ github.repository }}.**"