name: 'SWM GitHub Actions Basic'
# CD (Countinuous Delivery/Deploy) 차이.
on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: Say Hello World
      shell: bash
      run: |
        echo "Hello World from first job"
  
  second-job:
    name: 'Second Job'
    needs:
      - first-job

    runs-on: ubuntu-latest

    steps:
    - name: Say Hello World
      shell: bash
      run: |
        echo "Hello World from second job"